### ISSUE TITLE
Upgrade csproj to SDK format

### ISSUE THREAD

**Issue by persn** [adventuregamestudio/ags#1462]
SDK format is the new way of writing csproj files since after the .NET 5+ shift, although upgrading to .NET 5+ is not required in order to change the format. However if we ever will want to upgrade to .NET 5, 6, or later it is a requirement that the csproj has changed format. It's a bit tedious but that's how it is. I propose we just do it as soon as it's convenient since it'll be one less thing to think about in the event of a future proposed upgrade.

SDK format also offer various benefits in that it's less dense, has implicit variables, so for instance AGS.Types which is several hundred lines and difficult to read can be expressed as the following 
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <RootNamespace>AGS.Types</RootNamespace>
    <AssemblyName>AGS.Types</AssemblyName>
    <AssemblyOriginatorKeyFile>AGS.Types.snk</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="PropertyGridExtras\event.bmp" />
    <None Remove="Resources\roomdef.pal" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="PropertyGridExtras\event.bmp" />
    <EmbeddedResource Include="Resources\roomdef.pal" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Data" />
    <Reference Include="System.Design" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
  </ItemGroup>

</Project>
```

Caveat: VS2015 doesn't understand this format, so our minimum required visual studio would need an upgrade. I'm not exactly sure which version is minimum for the SDK format, but I believe it is VS2017. I can't speak for what kind of consequences an upgrade would have on the c++ side, for c# it's no issue.

**Comment by ericoporto** [comment]
@persn , does changing to csproj requires moving many files for the Editor or not at all?

**Comment by persn** [comment]
@ericoporto No there's no requirement for moving files, the only required changes can be seen directly on the csproj files. The AGS.Editor csproj would be neater if it was organized slightly different so we could utilize globbing to declare content and embedded resources, but that's entirely optional cleanup work.

I already have a branch that shows the needed changes, but I didn't open a PR on it because I wanted some consensus on whether we wanted to upgrade VS right now first. https://github.com/persn/ags/tree/csproj-sdk

**Comment by ericoporto** [comment]
I am fine with updating the project format, but currently it in our CI will be met with

> error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

Upgrading it also requires to upgrade our VS in the Windows Docker image. MS has more infor here (https://github.com/MicrosoftDocs/Virtualization-Documentation) but a lot of the docs haven't been updated in 5 years so I don't know how to make the newer VS (2019 for now) work there.

**Comment by ericoporto** [comment]
Finally got around upgrading the Windows Docker and @ivan-mogilko made VS2019 compatible project upgrades that are building.

@persn was the csproj upgrade you did hand-made or there is a button somewhere in Visual Studio that upgrades the old project files?

**Comment by persn** [comment]
@ericoporto handmade, I'm not sure if I still have that branch, I might have. However I'm AFK until the end of my Christmas vacation

**Comment by ericoporto** [comment]
I tried a tool called upgrade-assistant, and it gave me this https://github.com/ericoporto/ags/commit/c73ddd7d9f7e8270f886a2dd1689141b4c7d86af

```
dotnet tool install -g upgrade-assistant
upgrade-assistant upgrade
```

Running this in a directory with a `.csproj` file, it shows a text interface where you can use arrows and select an operation, and I chose the sdk-style upgrade, for each of the csproj files in the commit above.

I think maybe we need a label for build system or Visual Studio specifically.

**Comment by persn** [comment]
It seems that the dotnet SDK is not installed on the container. Newer C# has an improvement in the ecosystem so now you only need a light SDK to work with dotnet instead of a complete visual studio installation. It's assumed it would've installed automatically with vs2019 but maybe the C# workload was not selected in the install? https://dotnet.microsoft.com/en-us/download

**Comment by ericoporto** [comment]
Uhm, in theory the SDK is installed but it's the 4.6 one, I think it may be worth to upgrade to 4.8 framework before doing this - but not 4.8.1 for now. According to [docs](https://learn.microsoft.com/en-us/dotnet/framework/get-started/system-requirements), 4.8 is supported down to the same versions of Windows as the 4.6 we are using. I just mention this because it seems that .NET 4.8 is a little easier to install in a way compatible with vs2022.

> I'm not completely impressed with what the upgrade tool produced. My handmade upgrade was cleaner

Yeah, I am sure, I just wanted to check the windows container I am making for issues.

**Comment by persn** [comment]
@ericoporto Upgrading .net framework is fine by me

**Comment by ericoporto** [comment]
ok, I can't explain what is going on, but for some reason the SDK resolver keeps trying to look into the directory for new .NET SDKs, instead where .NET Framework SDK is actually installed. I tried both the vs2022 .NET Framework SDKs and the standalone ones and neither could be found. 

This works using the existing csproj just not any that is updated to SDK style.

I am not sure what is the specific difference that makes it not work in the Windows container while it does work on my actually desktop install.

**Comment by persn** [comment]
> ok, I can't explain what is going on, but for some reason the SDK resolver keeps trying to look into the directory for new .NET SDKs, instead where .NET Framework SDK is actually installed. I tried both the vs2022 .NET Framework SDKs and the standalone ones and neither could be found.

That's what I expect it to do, if any new SDK is installed the error message `Could not resolve SDK "Microsoft.NET.Sdk"` should go away, .NET 8 SDK would be fine, at least for testing purposes, I expect it to need any of the new SDKs because we're changing the csproj to the new "SDK" format.

I don't know what .NET framework (4.8.x and older) SDK is because .NET didn't start distributing SDKs until after that, everything before was distributed with Visual Studio, or Mono. If you run the command `dotnet --version` inside the container what do you get? If you have any valid installed SDKs it should produce a sensible message

> Edit: found something promising about using nuget to get the references

Interesting, I've seen those before in other projects. I didn't need them when building locally, but maybe it's because I have a lot of C# stuff installed on my computer

> I tried the handmade project for AGS.Controls, but it gives the error below

I was NOT expecting that error, impossible to comment on without getting myself to my dev PC and starting testing stuff out

**Comment by persn** [comment]
> Reading [its docs](https://learn.microsoft.com/en-us/dotnet/core/tools/) I don't quite get how to install it.

You get it automatically when any SDK is installed which makes it clear they aren't 

> agseditor csproj 

I fixed that in my handmade branch so don't worry about it. If you made the container able to compile at least one SDK project I think you done as much as you can do

**Comment by ericoporto** [comment]
Just to report, I tried installing both 8 and 9 .NET SDKs, but

- they don't install in the directory mentioned in the error message
- `dotnet` still doesn't work, but it is here in `C:\Program Files\dotnet` dir

Going there I used the command line

```
.\dotnet.exe --list-sdks
8.0.404 [C:\Program Files\dotnet\sdk]
```

Where is 9.0 sdk? I don't know... I will keep playing with this, I think it may be just adding that dir to PATH before calling MSBuild.

The tricky things about Windows Containers is **they don't restart**, so sometimes some install steps have to be done by hand or require command line tricks and parameters that aren't obvious.

**Comment by persn** [comment]
>  I think the issue of 9 is if the x64 utility finds the x86 install of a sdk it gives up finding the x64 version and thinks it doesn't exist. I need to only install the x64 version of 9 sdk or neither work....

Yes! A colleague of mine had that exact issue. Make sure only x64 is installed if possible or the PATH gets wonky. Nice find

That being said I would possibly only install SDK 8 since it has LTS and skip 9

**Comment by ericoporto** [comment]
> That being said I would possibly only install SDK 8 since it has LTS and skip 9

OK, now 8.0 is installed, dotnet tool is in but I still get the weird `error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.` when trying to build the solution in the windows container. My local vs install is also only vs2022 community and it seems the same, but it builds fine in it, the issue is just in the Windows container. I think I am almost there, I will keep playing with this. My guess is now it's something related to path or env vars, something msbuild specific.
