### ISSUE TITLE
ags3 regression: black morph font issues

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#835]
black morph: https://gamejolt.com/games/Black-Morph/231383/download/build/623519

already on the title screen, we notice that the font is broken (comparing 3.4.x release vs ags3 branch). as soon as we start playing, the in-game font is unreadable on the right half of the screen.

**Comment by sonneveld** [comment]
I'm assuming this is on Linux. Was your 3.4 linked to the system freetype library? What changeset of ags3? Have you tried git bisect to narrow it down? Do you have a screenshot?

**Comment by rofl0r** [comment]
> Linux.

right.

> Was your 3.4 linked to the system freetype library?

indeed.

> What changeset of ags3

latest at time of this writing.

> Have you tried git bisect to narrow it down

nope.

> Do you have a screenshot?

no, the download is only 20ish MB and not behind a login-wall.

**Comment by sonneveld** [comment]
> > Was your 3.4 linked to the system freetype library?
> 
> indeed.

Nice, what version was it? 




> > What changeset of ags3
> 
> latest at time of this writing.

Ok, I will assume c38b937273f21ec6002cde1dec9b1bead5f7833c





> > Do you have a screenshot?
> 
> no, the download is only 20ish MB and not behind a login-wall.

That's a shame. It would be good to be able to compare the output.

**Comment by i30817** [comment]
I didn't notice font problems in dark morph, thought there is some pixel corruption sometimes.

![Screenshot from 2019-06-13 04-52-08](https://user-images.githubusercontent.com/757900/59402643-3c22c300-8d97-11e9-8a83-fe32206c2b8f.png)

Tried both opengl and software thou software is slow enough here that it's unpleasant to use, and i'd rather not.

**Comment by i30817** [comment]
Title (on release):

![Screenshot from 2019-06-13 05-38-29](https://user-images.githubusercontent.com/757900/59404288-f0274c80-8d9d-11e9-910e-ee4f9d1f4c75.png)

You can see some pixel corruption under the owl.

**Comment by ivan-mogilko** [comment]
@i30817 thank you for pointing out, I tried this quickly yesterday but could not notice any difference myself.
TBH judging on ticket's description I was expecting something that stands out more. @rofl0r, is the above the issue that you observe?

**Comment by rofl0r** [comment]
i don't see much of a difference here, it's much more evident on the very first screen with the language selection, and when you read the speech by e.g. clicking on a reed.

**Comment by ivan-mogilko** [comment]
May be related, I just noticed that in "Heroine's Quest" the automatic outline of TTF fonts is cut at the font baseline, leaving lower parts of some letters non outlined. Supposedly alfont_text_height does not return full height, which is a regression compared to older builds.

This problem reproduces on both Linux and Windows, in post-3.5.0 master branch (works well in 3.5.0 on both these systems).

**Comment by ivan-mogilko** [comment]
@rofl0r This seem to not be an issue with the current master, and even final 3.5.0 release seem to look fine. I suspect this may have been fixed by building same alfont + freetype version embedded into the engine, but we forgot to retest and close this ticket.

Could you confirm this on your system when you've got time?

**Comment by rofl0r** [comment]
unfortunately still an issue on current master.
![](https://0x0.st/-5Yk.png)

unrelated: i noticed that current master by default runs the game in a window stretched to fullscreen resolution, instead of "native". i suppose that's due to the recent changes to config format ?

**Comment by ivan-mogilko** [comment]
> unfortunately still an issue on current master.

Now that you posted a screenshot, I've never seen anything like this neither on win or linux vm where I'm testing.
It looks like not just the font itself, but the parts of UI is distorted, because there's a part of a border missing on the left-bottom side (one could speculate that it's painted over by drawing a capital 'Y' letter though, not sure).

Do you still link to the system's FreeType library, or make it use one from the repo? (judging by the makefiles, it looks like it uses freetype all the time, but i may be missing something).

> unrelated: i noticed that current master by default runs the game in a window stretched to fullscreen resolution, instead of "native". i suppose that's due to the recent changes to config format ?

Iirc the default previously has been "max round multiplier", maybe I changed that by mistake. "Native" for this and many other games would be too small to play though.

**Comment by rofl0r** [comment]
> Which graphic renderer do you use, and does it depend on one at all?

according to log, it's using OpenGL 3.0, i need to figure out how to get the software renderer using the new config format.

> Do you still link to the system's FreeType library, or make it use one from the repo? (judging by the makefiles, it looks like it uses freetype all the time, but i may be missing something).

i cd to Engine, then run make. so to my knowledge this should build and use the included freetype version. SDL2 version is 2.0.16. but as reported the same kind of glitches were in 3.5.x branch too, so it's probably unrelated to SDL.
i do use musl libc though, vs glibc as used in most linux distros, and musl is more sensible when it comes to undefined behaviour. maybe you could test with an alpine linux vm ?

> "Native" for this and many other games would be too small to play though.

yeah, it's too small to play when you have a screen with high resolution, but only in windowed mode. that's why i hit ALT-enter to toggle fullscreen mode when i actually want to play, and then exit FS mode when i want to return to my desktop and e.g. minimize the window or take a screenshot of it.

**Comment by ivan-mogilko** [comment]
> i need to figure out how to get the software renderer using the new config format.

Renderer selection has not changed, it's still done like
<pre>
[graphics]
driver = software
</pre>

also it's possible to specify driver in command line as `--gfxdriver=software`.

**Comment by rofl0r** [comment]
> also it's possible to specify driver in command line as --gfxdriver=software.

ah, thanks. the issue is present with both "software" and "opengl" renderers.
now i noticed there seem to be other graphic glitches, for example you can see in my prev screenie that the top end of the character's hat is cut off.

btw the issue pointed out in the screenshots of https://github.com/adventuregamestudio/ags/issues/835#issuecomment-501546089 still exists, too. it's most blatant with the missing part of the R character.

**Comment by ivan-mogilko** [comment]
> now i noticed there seem to be other graphic glitches, for example you can see in my prev screenie that the top end of the character's hat is cut off.

I noticed this too, only with "ogl" renderer, this maybe is a problem with uneven scaling.

> btw the issue pointed out in the screenshots of #835 (comment) still exists, too. it's most blatant with the missing part of the R character.

Yes, I've decided to ignore for now as it seems to be not that serious. Also, on another occasion, the original game had some letters drawn incorrectly as opposed to the current version (at least on win).

**Comment by rofl0r** [comment]
> Yes, I've decided to ignore for now as it seems to be not that serious.

i'd argue it's most likely the same issue, and fixing one would fix (or at least lead to) the other.

**Comment by ivan-mogilko** [comment]
Iirc you were comparing the difference between 3.4.x and newer versions; when you compile 3.4.x, which freetype library do you link? Maybe it's the difference in how freetype loads that font.

**Comment by rofl0r** [comment]
> Iirc you were comparing the difference between 3.4.x and newer versions

that post is from another user. i dont think i had a 3.4.x version around at the time i filed this for comparison.

> when you compile 3.4.x, which freetype library do you link?

i'm not 100% sure but i think we added the old freetype sources to ags before 3.5.x release?

**Comment by ivan-mogilko** [comment]
> btw the issue pointed out in the screenshots of [#835 (comment)](https://github.com/adventuregamestudio/ags/issues/835#issuecomment-501546089) still exists, too. it's most blatant with the missing part of the R character.

I need to clarify this out, because as I retest and compare original windows game and latest master - I do not see any regression.

This is original game screenshot (windows engine v341):
![blackmorph-original-win](https://user-images.githubusercontent.com/1833754/141170243-c5558d03-f346-4f72-b2dd-fa5980c2c448.png)

This is windows engine v360 (latest master):
![blackmorph-ags360-win](https://user-images.githubusercontent.com/1833754/141170275-d9bd541e-2de0-48d5-9d4e-95681519b8eb.png)

This is linux engine v360 (latest master), run on Ubuntu:
![blackmorph-ags360-linux](https://user-images.githubusercontent.com/1833754/141170318-2978a927-f79d-442e-afc4-51e21e4f8fb1.png)


So apparently in the previous screenshots by @i30817 it is the 3.5.0 version that was matching the original game, and 3.4.3 was not for some reason.

**Comment by rofl0r** [comment]
> This is linux engine v360 (latest master), run on Ubuntu:

did you compile ags with cmake or makefile ? i could imagine that something (like an internal lib) was added to cmake build but not makefile - regarding the issue that fonts are almost unreadable as in the screenshot i posted when clicking on reeds.

**Comment by ivan-mogilko** [comment]
I use makefile because it's simplier for me; either directly (`cd Engine` then `make`), or the debian build script (debian/rules), which also runs same makefile and creates installation package.

This is the relevant scene with speech from Ubuntu:
![blackmorph2-ags360-linux](https://user-images.githubusercontent.com/1833754/141177266-892b64ca-0f08-4871-a7eb-7ffdc68b2310.png)

So at this point I imagine this might be related to a difference in system libs.

**Comment by rofl0r** [comment]
looks to me like the original:

```
md5sum Black\ Morph.exe 
eae9a8f2e6807c92f21399061a78304f  Black Morph.exe
```
filesize 16323122, Sep 25  2018 Black Morph.exe

**Comment by i30817** [comment]
Gezz, this was so long ago i don't even keep the games at hand anymore, but what ivan says about i having the order of conclusions wrong (3.5 fixed the fonts of 3.42) seems right - not because i tested in the original in windows but because that 'R' leg even to me originally seemed ugly.

In retrospect, it's probably the bug being fixed that changed those.
